# Generated by Django 4.0 on 2022-02-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
