# Generated by Django 4.0 on 2022-02-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
