# Generated by Django 4.0 on 2022-02-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
